In [1]:
from importlib import reload 
import simStarTrackerImage 

import numpy as np

In [2]:
reload(simStarTrackerImage)

In [3]:
st=simStarTrackerImage.SimStarTrackerImage(1096, 2048)
st.ra=249.534279 
st.dec=2.938149 
st.rot=120.916866

st.exptime = 0.1

In [4]:
#st.buildWCS(wcsFile='./ObsImage/Cam5_Altair_1.0.wcs')

st.buildWCS()
catalog = './Catalog/gsc.all'
stars=st.readStarCatalog(catalog)

2021-06-29T13:56:30.559 20 simStarTracker [simStarTrackerImage.py:59] Buiding WCS from empty
2021-06-29T13:56:30.560 20 simStarTracker [simStarTrackerImage.py:82] Rotate WCS by 120.916866 degrees.
2021-06-29T13:56:31.464 20 simStarTracker [simStarTrackerImage.py:146] Star catalog is ready

In [5]:
stars

,ra,dec,Vmag,source,x,y,ABmag,Jy,theta,rho,Nphoton
3931,242.460325,-3.466747,5.55,T,1050.382858,870.796806,5.57,21.478305,343.040754,525.223528,560.545999
3937,243.190387,-1.721943,7.46,T,946.084052,856.247352,7.48,3.698282,337.149439,431.985952,96.518654
3938,243.235604,-4.220914,6.27,T,1064.127773,928.946569,6.29,11.066238,349.564966,524.807615,288.809355
3940,243.310851,-1.402499,7.77,T,927.457108,852.981096,7.79,2.779713,335.739213,416.215284,72.545630
3941,243.356386,-4.051646,6.98,T,1052.521060,929.867828,7.00,5.754399,349.431425,513.227402,150.179708
...,...,...,...,...,...,...,...,...,...,...,...
38725,256.320417,0.702500,6.01,B,461.231601,1405.817958,6.03,14.060475,102.803066,391.552944,366.953688
38726,261.657917,-5.086667,4.54,B,584.502832,1833.095972,4.56,54.450265,87.416819,809.918977,1421.056210
38727,262.599167,-1.062500,5.31,B,363.362214,1760.722543,5.33,26.791683,104.069700,759.507220,699.215838
38728,267.328750,1.961111,6.47,B,74.018693,1908.716204,6.49,9.204496,118.179908,1003.683736,240.221158
38730,268.147500,1.305000,5.95,B,80.229830,1970.841541,5.97,14.859356,116.290853,1056.086093,387.803083

In [6]:
st.ra=249.606454
st.dec=3.089867
st.rot=120.923687

st.exptime = 0.1

In [7]:
st.buildWCS()
catalog = './Catalog/gsc.all'
stars=st.readStarCatalog(catalog)

2021-06-29T14:04:13.166 20 simStarTracker [simStarTrackerImage.py:59] Buiding WCS from empty
2021-06-29T14:04:13.168 20 simStarTracker [simStarTrackerImage.py:82] Rotate WCS by 120.923687 degrees.
2021-06-29T14:04:14.051 20 simStarTracker [simStarTrackerImage.py:146] Star catalog is ready

In [8]:
stars

,ra,dec,Vmag,source,x,y,ABmag,Jy,theta,rho,Nphoton
3931,242.460325,-3.466747,5.55,T,1059.743591,871.633033,5.57,21.478305,343.419582,533.944937,560.545999
3937,243.190387,-1.721943,7.46,T,955.357826,857.087903,7.48,3.698282,337.718968,440.227267,96.518654
3938,243.235604,-4.220914,6.27,T,1073.501171,929.808548,6.29,11.066238,349.838144,533.875932,288.809355
3940,243.310851,-1.402499,7.77,T,936.717533,853.822502,7.79,2.779713,336.356572,424.336778,72.545630
3941,243.356386,-4.051646,6.98,T,1061.883382,930.730643,7.00,5.754399,349.712853,522.278952,150.179708
...,...,...,...,...,...,...,...,...,...,...,...
38725,256.320417,0.702500,6.01,B,470.334467,1406.677112,6.03,14.060475,101.472536,390.478817,366.953688
38726,261.657917,-5.086667,4.54,B,593.584214,1834.067876,4.56,54.450265,86.779243,811.349422,1421.056210
38727,262.599167,-1.062500,5.31,B,372.461183,1761.517703,5.33,26.791683,103.388040,758.120200,699.215838
38728,267.328750,1.961111,6.47,B,83.259810,1909.253795,6.49,9.204496,117.698557,999.828848,240.221158
38730,268.147500,1.305000,5.95,B,89.460166,1971.367974,5.97,14.859356,115.827655,1052.504089,387.803083